// radical_data.js
// Array con los 214 radicales Kangxi revisados y estandarizados.

const radicalsData = [
    { id: 1, radical: "一", variants: [], pinyin: "yī", meaning: "Uno", examples: "丁 万 上 下" },
    { id: 2, radical: "丨", variants: [], pinyin: "shù/gǔn", meaning: "Línea vertical", examples: "个 中 丰 串 临" },
    { id: 3, radical: "丶", variants: [], pinyin: "diǎn/zhǔ", meaning: "Punto", examples: "丸 义 丹 为 主" },
    { id: 4, radical: "丿", variants: ["乀", "乁"], pinyin: "piě", meaning: "Trazo oblicuo", examples: "乂 乃 久 乇 乎" },
    { id: 5, radical: "乙", variants: ["乚", "乛"], pinyin: "yǐ", meaning: "Segundo", examples: "九 乞 乩 乱" },
    { id: 6, radical: "亅", variants: [], pinyin: "gōu/jué", meaning: "Gancho", examples: "了 争 事" },
    { id: 7, radical: "二", variants: [], pinyin: "èr", meaning: "Dos", examples: "亍 于 云 五 亚" },
    { id: 8, radical: "亠", variants: [], pinyin: "tóu", meaning: "Tapa superior", examples: "亡 亢 交 产 京" },
    { id: 9, radical: "人", variants: ["亻"], pinyin: "rén", meaning: "Persona", examples: "你 他 仕 仙 例" },
    { id: 10, radical: "儿", variants: [], pinyin: "ér/rén", meaning: "Piernas humanas", examples: "兀 元 兄 先 克" },
    { id: 11, radical: "入", variants: [], pinyin: "rù", meaning: "Entrar", examples: "內 全 氽" },
    { id: 12, radical: "八", variants: ["丷"], pinyin: "bā", meaning: "Ocho", examples: "兮 公 兰 关 兴" },
    { id: 13, radical: "冂", variants: [], pinyin: "jiǒng", meaning: "Recinto abierto", examples: "内 冋 再 冏 最" },
    { id: 14, radical: "冖", variants: [], pinyin: "mì", meaning: "Cubierta", examples: "写 军 农" },
    { id: 15, radical: "冫", variants: [], pinyin: "bīng", meaning: "Hielo", examples: "冰 况 冼 凊" },
    { id: 16, radical: "几", variants: [], pinyin: "jī/jǐ", meaning: "Banqueta", examples: "凡 凤" },
    { id: 17, radical: "凵", variants: [], pinyin: "qiǎn", meaning: "Contenedor abierto", examples: "凶 凸 凹 出 击" },
    { id: 18, radical: "刀", variants: ["⺈", "刂"], pinyin: "dāo", meaning: "Cuchillo", examples: "刅 分 切 划 刚" },
    { id: 19, radical: "力", variants: [], pinyin: "lì", meaning: "Fuerza", examples: "劝 办 加 务 动" },
    { id: 20, radical: "勹", variants: [], pinyin: "bāo", meaning: "Envolver", examples: "勺 勾 匀 包" },
    { id: 21, radical: "匕", variants: [], pinyin: "bǐ", meaning: "Cuchara ritual", examples: "化 北 匙" },
    { id: 22, radical: "匚", variants: [], pinyin: "fāng/xǐ", meaning: "Caja rectangular", examples: "匛 匤 匡 匢 匜" },
    { id: 23, radical: "匸", variants: [], pinyin: "xǐ", meaning: "Esconder", examples: "匹 区 医 匼" },
    { id: 24, radical: "十", variants: [], pinyin: "shí", meaning: "Diez", examples: "千 升 午 半" },
    { id: 25, radical: "卜", variants: [], pinyin: "bǔ", meaning: "Adivinación", examples: "卟 占 卡 卢 卤" },
    { id: 26, radical: "卩", variants: ["㔾"], pinyin: "jié", meaning: "Sello oficial", examples: "卫 卬 卯 印 却" },
    { id: 27, radical: "厂", variants: [], pinyin: "hǎn", meaning: "Acantilado", examples: "厄 厅 历 厉" },
    { id: 28, radical: "厶", variants: [], pinyin: "sī/mǒu", meaning: "Privado", examples: "去 县 参" },
    { id: 29, radical: "又", variants: [], pinyin: "yòu", meaning: "Mano derecha", examples: "叉 友 双 发 受" },
    { id: 30, radical: "口", variants: [], pinyin: "kǒu", meaning: "Boca", examples: "吃 叹 品 吵 叫" },
    { id: 31, radical: "囗", variants: [], pinyin: "wéi", meaning: "Recinto cerrado", examples: "围 团 国 囚 困" },
    { id: 32, radical: "土", variants: [], pinyin: "tǔ", meaning: "Tierra", examples: "在 地 城 型" },
    { id: 33, radical: "士", variants: [], pinyin: "shì", meaning: "Erudito", examples: "壮 仕 壬 声 志" },
    { id: 34, radical: "夂", variants: [], pinyin: "zhī/zhǐ", meaning: "Avanzar", examples: "处 复 备 冬" },
    { id: 35, radical: "夊", variants: [], pinyin: "suī", meaning: "Caminar lentamente", examples: "夌 复 変" },
    { id: 36, radical: "夕", variants: [], pinyin: "xī", meaning: "Atardecer", examples: "外 多 夜 夠" },
    { id: 37, radical: "大", variants: [], pinyin: "dà", meaning: "Grande", examples: "天 太 夫 央 头" },
    { id: 38, radical: "女", variants: [], pinyin: "nǚ", meaning: "Mujer", examples: "妈 好 始 姓 安" },
    { id: 39, radical: "子", variants: [], pinyin: "zǐ", meaning: "Niño", examples: "孔 字 季 学 孩" },
    { id: 40, radical: "宀", variants: [], pinyin: "mián", meaning: "Techo", examples: "宁 它 安 定 容" },
    { id: 41, radical: "寸", variants: [], pinyin: "cùn", meaning: "Pulgada", examples: "对 寺 寻 寿 导" },
    { id: 42, radical: "小", variants: ["⺍", "⺌"], pinyin: "xiǎo", meaning: "Pequeño", examples: "少 尔 尚 尝" },
    { id: 43, radical: "尢", variants: [], pinyin: "yóu/wāng", meaning: "Cojo", examples: "尤 尧 就 尴 尬" },
    { id: 44, radical: "尸", variants: [], pinyin: "shī", meaning: "Cadáver", examples: "尼 尽 局 居 层" },
    { id: 45, radical: "屮", variants: [], pinyin: "chè", meaning: "Brote vegetal", examples: "屯 屰" },
    { id: 46, radical: "山", variants: [], pinyin: "shān", meaning: "Montaña", examples: "岀 峰 岁 岛 岳" },
    { id: 47, radical: "巛", variants: ["川"], pinyin: "chuān", meaning: "Río", examples: "州 巡 巢" },
    { id: 48, radical: "工", variants: [], pinyin: "gōng", meaning: "Trabajo", examples: "左 巧 巩 巫" },
    { id: 49, radical: "己", variants: [], pinyin: "jǐ", meaning: "Uno mismo", examples: "纪 记 忌 改" },
    { id: 50, radical: "巾", variants: [], pinyin: "jīn", meaning: "Paño", examples: "巿 币 市 师" },
    { id: 51, radical: "干", variants: [], pinyin: "gān/gàn", meaning: "Interferir", examples: "平 年 并 幸" },
    { id: 52, radical: "幺", variants: ["么"], pinyin: "yāo", meaning: "Delgado", examples: "幻 幼 幽" },
    { id: 53, radical: "广", variants: [], pinyin: "guǎng", meaning: "Estructura amplia", examples: "座 庄 床 店" },
    { id: 54, radical: "廴", variants: [], pinyin: "yǐn", meaning: "Pasos largos", examples: "延 廷 建" },
    { id: 55, radical: "廾", variants: [], pinyin: "gǒng", meaning: "Manos juntas", examples: "开 异 弃 弄" },
    { id: 56, radical: "弋", variants: [], pinyin: "yì", meaning: "Estaca", examples: "式 弑" },
    { id: 57, radical: "弓", variants: [], pinyin: "gōng", meaning: "Arco", examples: "弟 引 张 弘 弯" },
    { id: 58, radical: "彐", variants: ["彑"], pinyin: "jì", meaning: "Hocico de cerdo", examples: "归 当 录 彖" },
    { id: 59, radical: "彡", variants: [], pinyin: "shān", meaning: "Pelos", examples: "形 彦 彩 影" },
    { id: 60, radical: "彳", variants: [], pinyin: "chì", meaning: "Pasos cortos", examples: "行 徐 律 很 往" },
    { id: 61, radical: "心", variants: ["忄", "⺗"], pinyin: "xīn", meaning: "Corazón", examples: "必 忆 忘 忙 快" },
    { id: 62, radical: "戈", variants: [], pinyin: "gē", meaning: "Alabarda", examples: "我 成 戒 战 或" },
    { id: 63, radical: "戶", variants: ["戸"], pinyin: "hù", meaning: "Puerta", examples: "房 所 扁 扇 扉" },
    { id: 64, radical: "手", variants: ["扌", "龵"], pinyin: "shǒu", meaning: "Mano", examples: "扔 扬 扛 扱 抱" },
    { id: 65, radical: "支", variants: [], pinyin: "zhī", meaning: "Rama", examples: "攰 攱 攲" },
    { id: 66, radical: "攴", variants: ["攵"], pinyin: "pū", meaning: "Golpear", examples: "收 改 政 故 敌" },
    { id: 67, radical: "文", variants: [], pinyin: "wén", meaning: "Cultura", examples: "齐 斌 斑 斓 斋" },
    { id: 68, radical: "斗", variants: [], pinyin: "dǒu", meaning: "Medida de capacidad", examples: "料 斛 斟 斜" },
    { id: 69, radical: "斤", variants: [], pinyin: "jīn", meaning: "Hacha", examples: "斧 断 斯 新 斩" },
    { id: 70, radical: "方", variants: [], pinyin: "fāng", meaning: "Cuadrado", examples: "施 旁 旋 旅 旗" },
    { id: 71, radical: "无", variants: [], pinyin: "wú", meaning: "No tener", examples: "既" },
    { id: 72, radical: "日", variants: [], pinyin: "rì", meaning: "Sol", examples: "时 早 明 是 晩" },
    { id: 73, radical: "曰", variants: [], pinyin: "yuē", meaning: "Decir", examples: "曲 更 曾" },
    { id: 74, radical: "月", variants: [], pinyin: "yuè", meaning: "Luna (o 'carne' en posición izquierda)", examples: "服 朋 青 朝 明" },
    { id: 75, radical: "木", variants: ["朩"], pinyin: "mù", meaning: "Árbol", examples: "森 林 相 根 本" },
    { id: 76, radical: "欠", variants: [], pinyin: "qiàn", meaning: "Bostezar", examples: "次 欢 欣 歆 欲" },
    { id: 77, radical: "止", variants: [], pinyin: "zhǐ", meaning: "Detenerse", examples: "正 此 步 武 歧" },
    { id: 78, radical: "歹", variants: ["歺"], pinyin: "dǎi", meaning: "Maldad", examples: "死 歾 殃 殉 殆" },
    { id: 79, radical: "殳", variants: [], pinyin: "shū", meaning: "Arma larga", examples: "段 殷 殴" },
    { id: 80, radical: "毋", variants: [], pinyin: "wú", meaning: "Prohibición", examples: "每 毒" },
    { id: 81, radical: "比", variants: [], pinyin: "bǐ", meaning: "Comparar", examples: "毕 庇 毙" },
    { id: 82, radical: "毛", variants: [], pinyin: "máo", meaning: "Pelo", examples: "毫 毡 笔 毯" },
    { id: 83, radical: "氏", variants: [], pinyin: "shì", meaning: "Apellido", examples: "民 氓" },
    { id: 84, radical: "气", variants: [], pinyin: "qì", meaning: "Aliento", examples: "氲 氧 氢" },
    { id: 85, radical: "水", variants: ["氵", "氺"], pinyin: "shuǐ", meaning: "Agua", examples: "海 河 湖 江 洗" },
    { id: 86, radical: "火", variants: ["灬"], pinyin: "huǒ", meaning: "Fuego", examples: "灯 炎 热 点 然" },
    { id: 87, radical: "爪", variants: ["爫"], pinyin: "zhǎo/zhuǎ", meaning: "Garra", examples: "爬 爱" },
    { id: 88, radical: "父", variants: [], pinyin: "fù", meaning: "Padre", examples: "爷 爸" },
    { id: 89, radical: "爻", variants: [], pinyin: "yáo", meaning: "Líneas cruzadas", examples: "爼 爽" },
    { id: 90, radical: "爿", variants: [], pinyin: "qiáng", meaning: "Tabla partida", examples: "牀" },
    { id: 91, radical: "片", variants: [], pinyin: "piàn", meaning: "Lámina", examples: "版 牌" },
    { id: 92, radical: "牙", variants: [], pinyin: "yá", meaning: "Diente", examples: "呀 芽 雅" },
    { id: 93, radical: "牛", variants: ["牜", "⺧"], pinyin: "niú", meaning: "Buey", examples: "牟 牤 牧 物 牲" },
    { id: 94, radical: "犬", variants: ["犭"], pinyin: "quǎn", meaning: "Perro", examples: "犮 犯 犷 狂 狗" },
    { id: 95, radical: "玄", variants: [], pinyin: "xuán", meaning: "Profundo", examples: "率 玆" },
    { id: 96, radical: "玉", variants: ["王", "玊"], pinyin: "yù", meaning: "Jade", examples: "珍 现 琴 莹 玺" },
    { id: 97, radical: "瓜", variants: [], pinyin: "guā", meaning: "Calabaza", examples: "瓢 瓣" },
    { id: 98, radical: "瓦", variants: [], pinyin: "wǎ", meaning: "Teja", examples: "瓶 瓷 瓮" },
    { id: 99, radical: "甘", variants: [], pinyin: "gān", meaning: "Dulce", examples: "甚 甜 某" },
    { id: 100, radical: "生", variants: [], pinyin: "shēng", meaning: "Nacer", examples: "甠 甡 甥" },
    { id: 101, radical: "用", variants: [], pinyin: "yòng", meaning: "Usar", examples: "甬 甭 甫" },
    { id: 102, radical: "田", variants: [], pinyin: "tián", meaning: "Campo", examples: "男 甸 画 畅 界" },
    { id: 103, radical: "疋", variants: ["⺪"], pinyin: "pǐ", meaning: "Rollo de tela", examples: "胥 疍 疏 疎" },
    { id: 104, radical: "疒", variants: [], pinyin: "bìng/nè", meaning: "Enfermedad", examples: "病 疔 疤 疫 疯" },
    { id: 105, radical: "癶", variants: [], pinyin: "bō", meaning: "Pasos alternados", examples: "癷 癸 登" },
    { id: 106, radical: "白", variants: [], pinyin: "bái", meaning: "Blanco", examples: "百 的 皇 皁 皓" },
    { id: 107, radical: "皮", variants: [], pinyin: "pí", meaning: "Piel", examples: "皱 皲" },
    { id: 108, radical: "皿", variants: [], pinyin: "mǐn", meaning: "Recipiente", examples: "盂 益 盆 监 盈" },
    { id: 109, radical: "目", variants: ["⺫"], pinyin: "mù", meaning: "Ojo", examples: "盯 相 盲 看 眠" },
    { id: 110, radical: "矛", variants: [], pinyin: "máo", meaning: "Lanza", examples: "矜 䂊" },
    { id: 111, radical: "矢", variants: [], pinyin: "shǐ", meaning: "Flecha", examples: "矣 知 矩 矫 矬" },
    { id: 112, radical: "石", variants: [], pinyin: "shí", meaning: "Piedra", examples: "码 破 硌 硏 硬" },
    { id: 113, radical: "示", variants: ["礻"], pinyin: "shì", meaning: "Espíritu", examples: "礼 社 视 禁 祭" },
    { id: 114, radical: "禸", variants: [], pinyin: "róu", meaning: "Huella", examples: "禹 禺 离" },
    { id: 115, radical: "禾", variants: [], pinyin: "hé", meaning: "Cereal", examples: "秀 秋 种 秒 租" },
    { id: 116, radical: "穴", variants: [], pinyin: "xuè", meaning: "Cueva", examples: "穷 究 空 穿 突" },
    { id: 117, radical: "立", variants: [], pinyin: "lì", meaning: "Pararse", examples: "站 竞 章 竖 端" },
    { id: 118, radical: "竹", variants: ["⺮"], pinyin: "zhú", meaning: "Bambú", examples: "笑 笛 第 竿 等" },
    { id: 119, radical: "米", variants: [], pinyin: "mǐ", meaning: "Arroz", examples: "粮 类 粉 粤 籽" },
    { id: 120, radical: "糸", variants: ["糹", "纟"], pinyin: "sī", meaning: "Seda", examples: "红 纪 组 系 紧" },
    { id: 121, radical: "缶", variants: [], pinyin: "fǒu", meaning: "Jarra", examples: "缺 缸 罂" },
    { id: 122, radical: "网", variants: ["罒"], pinyin: "wǎng", meaning: "Red", examples: "罗 罚 罢 罪" },
    { id: 123, radical: "羊", variants: ["⺶", "⺷"], pinyin: "yáng", meaning: "Oveja", examples: "美 着 羞 群 羚" },
    { id: 124, radical: "羽", variants: [], pinyin: "yǔ", meaning: "Pluma", examples: "翠 翁 耀 翔" },
    { id: 125, radical: "老", variants: ["耂"], pinyin: "lǎo", meaning: "Viejo", examples: "者 耄 考" },
    { id: 126, radical: "而", variants: [], pinyin: "ér", meaning: "Y", examples: "耍 耐" },
    { id: 127, radical: "耒", variants: [], pinyin: "lěi", meaning: "Arado", examples: "耔 耗 耕 耘" },
    { id: 128, radical: "耳", variants: [], pinyin: "ěr", meaning: "Oreja", examples: "聊 聆 聒 联 耿" },
    { id: 129, radical: "聿", variants: ["⺺"], pinyin: "yù", meaning: "Pincel", examples: "肃 肆 肄 肇" },
    { id: 130, radical: "肉", variants: ["⺼"], pinyin: "ròu", meaning: "Carne", examples: "肖 肘 肚 腐" },
    { id: 131, radical: "臣", variants: [], pinyin: "chén", meaning: "Ministro", examples: "卧 藏" },
    { id: 132, radical: "自", variants: [], pinyin: "zì", meaning: "Nariz", examples: "臬 臭" },
    { id: 133, radical: "至", variants: [], pinyin: "zhì", meaning: "Llegar", examples: "致 臻" },
    { id: 134, radical: "臼", variants: [], pinyin: "jiù", meaning: "Mortero", examples: "臾 舀 舂" },
    { id: 135, radical: "舌", variants: [], pinyin: "shé", meaning: "Lengua", examples: "舍 舐 舔" },
    { id: 136, radical: "舛", variants: [], pinyin: "chuǎn", meaning: "Conflicto", examples: "舜" },
    { id: 137, radical: "舟", variants: [], pinyin: "zhōu", meaning: "Bote", examples: "航 船 般 舱 舫" },
    { id: 138, radical: "艮", variants: [], pinyin: "gèn", meaning: "Montaña", examples: "良 艰 根 跟" },
    { id: 139, radical: "色", variants: [], pinyin: "sè", meaning: "Color", examples: "艳" },
    { id: 140, radical: "艸", variants: ["艹"], pinyin: "cǎo", meaning: "Hierba", examples: "花 菜 茶 茬 草" },
    { id: 141, radical: "虍", variants: [], pinyin: "hū/hǔ", meaning: "Tigre", examples: "虏 虎 虐 虔 虑" },
    { id: 142, radical: "虫", variants: [], pinyin: "chóng", meaning: "Insecto", examples: "蛇 蚊 蛋 蚤 蚀" },
    { id: 143, radical: "血", variants: [], pinyin: "xuě", meaning: "Sangre", examples: "恤 衅" },
    { id: 144, radical: "行", variants: [], pinyin: "xíng", meaning: "Caminar", examples: "衍 衔 街" },
    { id: 145, radical: "衣", variants: ["衤"], pinyin: "yī", meaning: "Ropa", examples: "表 袋 袓 衷 袄" },
    { id: 146, radical: "襾", variants: ["覀"], pinyin: "yà/xī", meaning: "Cubrir", examples: "要 覆 覃" },
    { id: 147, radical: "見", variants: ["见"], pinyin: "jiàn", meaning: "Ver", examples: "观 规 觉 览" },
    { id: 148, radical: "角", variants: [], pinyin: "jiǎo", meaning: "Cuerno", examples: "解 触" },
    { id: 149, radical: "言", variants: ["讠"], pinyin: "yán", meaning: "Hablar", examples: "计 讨 记 讲 识" },
    { id: 150, radical: "谷", variants: [], pinyin: "gǔ", meaning: "Valle", examples: "豁" },
    { id: 151, radical: "豆", variants: [], pinyin: "dòu", meaning: "Frijol", examples: "豌 豉" },
    { id: 152, radical: "豕", variants: [], pinyin: "shǐ", meaning: "Cerdo", examples: "豚 豪 象" },
    { id: 153, radical: "豸", variants: [], pinyin: "zhì", meaning: "Gato salvaje", examples: "豹 豺 貌" },
    { id: 154, radical: "貝", variants: ["贝"], pinyin: "bèi", meaning: "Concha", examples: "贞 负 贡 责 财" },
    { id: 155, radical: "赤", variants: [], pinyin: "chì", meaning: "Rojo", examples: "赦 赫" },
    { id: 156, radical: "走", variants: [], pinyin: "zǒu", meaning: "Correr", examples: "赶 起 超 越" },
    { id: 157, radical: "足", variants: ["⻊"], pinyin: "zú", meaning: "Pie", examples: "跃 跑 路 跳" },
    { id: 158, radical: "身", variants: [], pinyin: "shēn", meaning: "Cuerpo", examples: "躬 躺 躲" },
    { id: 159, radical: "車", variants: ["车"], pinyin: "chē", meaning: "Carruaje", examples: "轧 轨 软 轮 轻" },
    { id: 160, radical: "辛", variants: [], pinyin: "xīn", meaning: "Amargo", examples: "辜 辣 辞 辟" },
    { id: 161, radical: "辰", variants: [], pinyin: "chén", meaning: "Tiempo", examples: "晨 辱 振 震" },
    { id: 162, radical: "辵", variants: ["辶"], pinyin: "chuò", meaning: "Caminar", examples: "边 达 过 运 远" },
    { id: 163, radical: "邑", variants: ["阝"], pinyin: "yì", meaning: "Ciudad", examples: "那 邦 邮 郊 邕" },
    { id: 164, radical: "酉", variants: [], pinyin: "yǒu", meaning: "Alcohol", examples: "酒 酱 酷" },
    { id: 165, radical: "釆", variants: [], pinyin: "biàn", meaning: "Distinguir", examples: "采 釉 释" },
    { id: 166, radical: "里", variants: [], pinyin: "lǐ", meaning: "Aldea", examples: "重 野 量" },
    { id: 167, radical: "金", variants: ["钅"], pinyin: "jīn", meaning: "Metal", examples: "银 钉 钟 钥 鉴" },
    { id: 168, radical: "長", variants: ["长"], pinyin: "cháng", meaning: "Largo", examples: "张 帐 账" },
    { id: 169, radical: "門", variants: ["门"], pinyin: "mén", meaning: "Puerta", examples: "间 闪 闯 闭 闹" },
    { id: 170, radical: "阜", variants: ["阝"], pinyin: "fù", meaning: "Montículo", examples: "陡 陆 防 际 队" },
    { id: 171, radical: "隶", variants: [], pinyin: "lì", meaning: "Esclavo", examples: "" },
    { id: 172, radical: "隹", variants: [], pinyin: "zhuī", meaning: "Pájaro", examples: "难 雀 集 雇" },
    { id: 173, radical: "雨", variants: ["⻗"], pinyin: "yǔ", meaning: "Lluvia", examples: "雪 零 雷 雾" },
    { id: 174, radical: "青", variants: [], pinyin: "qīng", meaning: "Azul-verde", examples: "靓 靖 静" },
    { id: 175, radical: "非", variants: [], pinyin: "fēi", meaning: "No ser", examples: "靠 靡" },
    { id: 176, radical: "面", variants: [], pinyin: "miàn", meaning: "Rostro", examples: "靥 腼" },
    { id: 177, radical: "革", variants: [], pinyin: "gé", meaning: "Cuero", examples: "靴 鞋" },
    { id: 178, radical: "韋", variants: ["韦"], pinyin: "wěi", meaning: "Cuero curtido", examples: "韧 韩 韫" },
    { id: 179, radical: "韭", variants: [], pinyin: "jiǔ", meaning: "Puerro", examples: "瀣" },
    { id: 180, radical: "音", variants: [], pinyin: "yīn", meaning: "Sonido", examples: "章 竟 歆 韵" },
    { id: 181, radical: "頁", variants: ["页"], pinyin: "yè", meaning: "Página", examples: "顶 项 须 顺" },
    { id: 182, radical: "風", variants: ["风"], pinyin: "fēng", meaning: "Viento", examples: "飒 飓 飘" },
    { id: 183, radical: "飛", variants: ["飞"], pinyin: "fēi", meaning: "Volar", examples: "" },
    { id: 184, radical: "食", variants: ["饣"], pinyin: "shí", meaning: "Comida", examples: "饥 饮 饱 饰 餐" },
    { id: 185, radical: "首", variants: [], pinyin: "shǒu", meaning: "Cabeza", examples: "馗" },
    { id: 186, radical: "香", variants: [], pinyin: "xiāng", meaning: "Fragancia", examples: "馥 馨" },
    { id: 187, radical: "馬", variants: ["马"], pinyin: "mǎ", meaning: "Caballo", examples: "驰 驹 骂 骇 驳" },
    { id: 188, radical: "骨", variants: [], pinyin: "gǔ", meaning: "Hueso", examples: "骸 骷 骰" },
    { id: 189, radical: "高", variants: [], pinyin: "gāo", meaning: "Alto", examples: "髚" },
    { id: 190, radical: "髟", variants: [], pinyin: "biāo", meaning: "Cabello largo", examples: "髦 鬃 鬓" },
    { id: 191, radical: "鬥", variants: [], pinyin: "dòu", meaning: "Luchar", examples: "鬧 鬦" },
    { id: 192, radical: "鬯", variants: [], pinyin: "chàng", meaning: "Bebida ritual", examples: "" },
    { id: 193, radical: "鬲", variants: [], pinyin: "lì", meaning: "Vasija", examples: "鬳 鬴 鬵 鬷" },
    { id: 194, radical: "鬼", variants: [], pinyin: "guǐ", meaning: "Espíritu", examples: "魂 魄 魅" },
    { id: 195, radical: "魚", variants: ["鱼"], pinyin: "yú", meaning: "Pez", examples: "鲜 鲈 鲑" },
    { id: 196, radical: "鳥", variants: ["鸟"], pinyin: "niǎo", meaning: "Ave", examples: "鸡 鸦 鸭" },
    { id: 197, radical: "鹵", variants: ["卤"], pinyin: "lǔ", meaning: "Sal", examples: "" },
    { id: 198, radical: "鹿", variants: [], pinyin: "lù", meaning: "Ciervo", examples: "麒 麓 麋" },
    { id: 199, radical: "麥", variants: ["麦"], pinyin: "mài", meaning: "Trigo", examples: "麸" },
    { id: 200, radical: "麻", variants: [], pinyin: "má", meaning: "Cáñamo", examples: "麾 磨 魔" },
    { id: 201, radical: "黄", variants: [], pinyin: "huáng", meaning: "Amarillo", examples: "横 磺 簧" },
    { id: 202, radical: "黍", variants: [], pinyin: "shǔ", meaning: "Mijo", examples: "黎 黏" },
    { id: 203, radical: "黑", variants: [], pinyin: "hēi", meaning: "Negro", examples: "墨 黔 默 黛" },
    { id: 204, radical: "黹", variants: [], pinyin: "zhǐ", meaning: "Bordado", examples: "" },
    { id: 205, radical: "黽", variants: ["黾"], pinyin: "mǐn/měng", meaning: "Rana", examples: "鼋" },
    { id: 206, radical: "鼎", variants: [], pinyin: "dǐng", meaning: "Caldero ritual", examples: "" },
    { id: 207, radical: "鼓", variants: [], pinyin: "gǔ", meaning: "Tambor", examples: "" },
    { id: 208, radical: "鼠", variants: [], pinyin: "shǔ", meaning: "Rata", examples: "" },
    { id: 209, radical: "鼻", variants: [], pinyin: "bí", meaning: "Nariz", examples: "鼾 齁" },
    { id: 210, radical: "齊", variants: ["齐"], pinyin: "qí", meaning: "Uniforme", examples: "挤 剂 济" },
    { id: 211, radical: "齒", variants: ["齿"], pinyin: "chǐ", meaning: "Diente", examples: "龄 龅" },
    { id: 212, radical: "龍", variants: ["龙"], pinyin: "lóng", meaning: "Dragón", examples: "龚 笼 珑" },
    { id: 213, radical: "龜", variants: ["龟"], pinyin: "guī", meaning: "Tortuga", examples: "" },
    { id: 214, radical: "龠", variants: [], pinyin: "yuè", meaning: "Flauta", examples: "" }
];

// Instrucciones:
// 1. Copia todo este contenido.
// 2. Reemplaza el archivo radical_data.js existente.
// 3. Asegúrate de cargarlo antes de cualquier script que lo utilice.